compressionLevel: mixed
enableGlobalCache: false
nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-4.4.0.cjs

npmScopes:
  pendle:
    npmAlwaysAuth: true
    npmAuthToken: "${PENDLE_SDK_BOROS_NPM_AUTH_TOKEN}"
    npmPublishRegistry: "https://registry.npmjs.org/"
    npmRegistryServer: "https://registry.npmjs.org/"
